dentist/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('appointment/', views.appointment, name="appointment"),
    path('contact/', views.contact, name="contact"),
    path('pricing/', views.pricing, name="pricing"),
    path('service/', views.service, name="service"),
]

frontend/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    service_name= models.CharField(max_length=200)
    stage = models.CharField(max_length = 50)
    price = models.FloatField()

    def __str__(self):
        return self.service_name

class Service(models.Model):
    service_available= models.CharField(max_length=200)
    details= models.TextField()
    images= models.ImageField(upload_to='media')

    def __str__(self):
        return self.service_available
#
class Ourdentist(models.Model):
    name= models.CharField(max_length=200)
    specialization= models.CharField(max_length=200)
    email= models.EmailField(max_length=200)
    facebook = models.URLField('facebook Address', blank=True)
    twitter = models.URLField('twitter Address', blank=True)
    images = models.ImageField(upload_to='media')

    def __str__(self):
        return self.name

class Testimony(models.Model):
    name= models.CharField(max_length=200)
    review= models.TextField()
    images = models.ImageField(upload_to='media')

    def __str__(self):
        return self.name


class Appointment(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name= models.CharField(max_length=20)
    your_phone = models.IntegerField()
    email= models.EmailField(max_length=50)
    address= models.CharField(max_length=50)
    time = models.CharField(max_length=50)
    date = models.CharField(max_length=50)
    message= models.TextField(max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

frontend/views.py
from django.shortcuts import render
from django.core.mail import send_mail

from .models import Category, Ourdentist, Testimony, Service, Appointment


def index(request):
    if request.method == "POST":
        your_name = request.POST['your-name']
        your_phone = request.POST['your-phone']
        your_email = request.POST['your-email']
        your_address = request.POST['your-address']
        your_time = request.POST['your-time']
        your_schedule = request.POST['your-schedule']
        your_message = request.POST['your-message']
        data= Appointment(name=your_name,your_phone=your_phone,email=your_email,address=your_address,time=your_time,date=your_schedule,message=your_message)
        data.save()
        return render(request, 'appointment.html', {
            'your_name': your_name,
            'your_phone': your_phone,
            'your_email': your_email,
            'your_address': your_address,
            'your_time': your_time,
            'your_schedule': your_schedule,
            'your_message': your_message,

        })
    category = Category.objects.all()
    testimony= Testimony.objects.all()
    ourdentist= Ourdentist.objects.all()
    context = {
        'category': category,
         'testimony': testimony,
        'ourdentist': ourdentist
    }
    return render(request,'index.html', context)

def contact(request):
    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        #send mail
        send_mail(
            message_name, #subject
            message,      #message"
            message_email,   #sender's email
            ['richardjose1252@gmail.com'], #reciever's email
        )
        return render(request, 'contact.html', {'message_name': message_name})
    else:
        return render(request, 'contact.html', {})


def service(request):
    service = Service.objects.all()
    context = {
        'service': service
    }

    return render(request, 'service.html', context)

def about(request):
    ourdentist = Ourdentist.objects.all()
    context = {
        'ourdentist': ourdentist
    }
    return render(request, 'about.html', context)

def appointment(request):
    # if request.method == "POST":
    #     your_name = request.POST['your-name']
    #     your_phone = request.POST['your-phone']
    #     your_email = request.POST['your-email']
    #     your_address = request.POST['your-address']
    #     your_time = request.POST['your-time']
    #     your_schedule = request.POST['your-schedule']
    #     your_message = request.POST['your-message']
    #
    #     # #send mail
    #     # send_mail(
    #     #     message_name, #subject
    #     #     message,      #message"
    #     #     message_email,   #sender's email
    #     #     ['richardjose1252@gmail.com'], #reciever's email
    #     # )
    #     return render(request, 'appointment.html', {
    #         'your_name': your_name,
    #         'your_phone': your_phone,
    #         'your_email': your_email,
    #         'your_address': your_address,
    #         'your_time': your_time,
    #         'your_schedule': your_schedule,
    #         'your_message': your_message,
    #
    #         })
    # else:
        return render(request, 'index.html', {})

def pricing(request):
    category = Category.objects.all()
    context= {
        'category': category
    }
    return render(request, 'pricing.html',context)

frontend/templates/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">About Us</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">About Us</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ****** About Us Area Start ******* -->
  <section class="dento-about-us-area mt-70">
    <div class="container">
      <div class="row align-items-center">
        <!-- About Us Thumbnail -->
        <div class="col-12 col-md-6">
          <div class="about-us-thumbnail mb-50">
            <img src="{% static 'img/bg-img/15.jpg' %}" alt="">
          </div>
        </div>
        <!-- About Content -->
        <div class="col-12 col-md-6">
          <div class="about-us-content mb-50">
            <!-- Section Heading -->
            <div class="section-heading">
              <h2>About Us</h2>
              <div class="line"></div>
            </div>
            <p>Vestibulum condimentum, risus sedones honcus rutrum, salah lacus mollis zurna, nec finibusmi velit advertisis. Proin vitae odin quis magna aliquet laciniae. Etiam auctor, nisi vel. Pellentesque ultrices nisl quam iaculis, nec pulvinar
              augue.</p>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Experience Dentist</h6>
              <div id="bar1" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="80"></span>
              </div>
            </div>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Modern Equipment</h6>
              <div id="bar2" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="65"></span>
              </div>
            </div>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Friendly Staff</h6>
              <div id="bar3" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="85"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ****** About Us Area End ****** -->

  <div class="container">
    <div class="dento-border clearfix"></div>
  </div>

  <!-- Cool Facts Area Start -->
  <section class="dento-cta-area">
    <div class="container">
      <div class="row">
        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_genius"></i>
            <h2><span class="counter">20</span></h2>
            <h5>Years Of Experience</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_heart_alt"></i>
            <h2><span class="counter">700</span>+</h2>
            <h5>Happy Patients</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_book_alt"></i>
            <h2><span class="counter">120</span></h2>
            <h5>Certificate</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_id"></i>
            <h2><span class="counter">40</span>+</h2>
            <h5>Dentist</h5>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Cool Facts Area End -->

<section class="dentist-area section-padding-100-0">
    <div class="container">
      <div class="row">
        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>Our Dentist</h2>
            <div class="line"></div>
          </div>
        </div>
      </div>
      <div class="row">
        <!-- Single Dentist Area -->
        {% for rs in ourdentist %}
        <div class="col-12 col-sm-6 col-md-4">
          <div class="single-dentist-area mb-100">
            <img src="{{rs.images.url}}" alt="">
            <!-- Dentist Content -->
            <div class="dentist-content">
              <!-- Social Info -->
              <div class="dentist-social-info">
                <a href="{{rs.facebook}}"><i class="fa fa-facebook"></i></a>
                <a href="{{rs.twitter}}"><i class="fa fa-twitter"></i></a>
                <a href="mailto:{{rs.email}}"><i class="fa fa-google-plus"></i></a>
              </div>
              <!-- Dentist Info -->
              <div class="dentist-info bg-gradient-overlay">
                <h5>"{{rs.name}}"</h5>
                <p>"{{rs.specialization}}"</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!-- ***** Dento Dentist Area End ***** -->
  {% endblock %}

frontend/templates/appointment.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% block title %}set appointment with Dr RICHARD{% endblock %}
{% block meta_description %}your health is my most concern{% endblock %}

  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">Appointment</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Contact</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->
<!-- ***** appointment review Area starts ***** -->


<center>
    <h1>Review your information</h1>
    <strong> Name: {{your_name}}</strong><br/>
     <strong>Phone: {{your_phone}}</strong><br/>
     <strong>Email: {{your_email}}</strong><br/>
     <strong>Address: {{your_address}}</strong><br/>
     <strong>Time: {{your_time}}</strong><br/>
     <strong>Date: {{your_schedule}}</strong><br/>
     <strong>Message: {{your_message}}</strong><br/>
</center>

<br/><br/>
<center><strong>We would contact you soon to confirm your appointment</strong></center>

<br/><br/><br/><br/>
<!-- ***** appointment review Area End ***** -->
{% endblock %}

frontend/templates/base.html
    <!DOCTYPE html>
    <html lang="en">
    {% load static %}

    <head>
      <meta charset="UTF-8">
      <meta name="description" content={% block meta_description %}"DR. RICHARD, your close dentist"{% endblock %}>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Title -->
      <title>{% block title %}"DR. RICHARD, your close dentist"{% endblock %}</title>

      <!-- Favicon -->
      <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

      <!-- Core Stylesheet -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

    </head>

    <body>
      <!-- Preloader -->
      <div id="preloader">
        <div class="preload-content">
          <div id="dento-load"></div>
        </div>
      </div>

      <!-- ***** Header Area Start ***** -->
      <header class="header-area">
        <!-- Top Header Area -->
        <div class="top-header-area">
          <div class="container h-100">
            <div class="row h-100 align-items-center">
              <!-- Top Content -->
              <div class="col-6 col-md-9 col-lg-8">
                <div class="top-header-content">
                  <a href="#" data-toggle="tooltip" data-placement="bottom" title="St Finbarr's College Rd, Akoka 102216, Lagos, Nigeria"><i class="fa fa-map-marker"></i> <span>St Finbarr's College Rd, Akoka 102216, Lagos, Nigeria</span></a>
                  <a href="#" data-toggle="tooltip" data-placement="bottom" title="info.dento@gmail.com"><i class="fa fa-envelope"></i> <span>info.dento@gmail.com</span></a>
                </div>
              </div>
              <!-- Top Header Social Info -->
              <div class="col-6 col-md-3 col-lg-4">
                <div class="top-header-social-info text-right">
                  <a href="" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>
                  <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                  <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                  <a href="#" data-toggle="tooltip" data-placement="bottom" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                  <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Top Header End -->

        <!-- Main Header Start -->
        <div class="main-header-area">
          <div class="classy-nav-container breakpoint-off">
            <div class="container">
              <!-- Classy Menu -->
              <nav class="classy-navbar justify-content-between" id="dentoNav">

                <!-- Logo -->
                <a class="nav-brand" href="{% url 'frontend:index' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>

                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                  <span class="navbarToggler"><span></span><span></span><span></span></span>
                </div>

                <!-- Menu -->
                <div class="classy-menu">

                  <!-- Close Button -->
                  <div class="classycloseIcon">
                    <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                  </div>

                  <!-- Nav Start -->
                  <div class="classynav">
                    <ul id="nav">
                      <li><a href="{% url 'frontend:index' %}">Home</a></li>
                      <li><a href="{% url 'frontend:about' %}">About</a></li>
                      <li><a href="{% url 'frontend:service' %}">Service</a></li>
                      <li><a href="{% url 'frontend:pricing' %}">Pricing</a></li>
                      <li><a href="{% url 'frontend:contact' %}">Contact</a></li>

                    </ul>
                  </div>
                  <!-- Nav End -->
                </div>
            </div>
          </div>
        </div>
      </header>
      <!-- ***** Header Area End ***** -->

      {% block content %}

      {% endblock %}

       <!-- ***** Footer Area Start ***** -->
      <footer class="footer-area bg-img bg-gradient-overlay" style="background-image: url({%static 'img/bg-img/3.jpg' %});">
        <div class="container">
          <div class="row">
            <!-- Single Footer Widget -->
            <div class="col-12 col-sm-6 col-lg-4">
              <div class="single-footer-widget">
                <a href="./index.html" class="d-block mb-4"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                <p>Etiam sutor risus, dapibus act elefend katen, lacinia sitamet denim. Mauris sagittis kansa interdum dignissim.</p>
                <div class="footer-contact">
                  <p><i class="icon_pin"></i> St Finbarr's College Rd, Akoka 102216, Lagos, Nigeria</p>
                  <p><i class="icon_phone"></i> +234. 2252. 2250. 125</p>
                  <i class="icon_mail"></i><a href="mailto: info.dento@gmail.com">Send Email</a>
                </div>
              </div>
            </div>

            <!-- Single Footer Widget -->
            <div class="col-12 col-sm-6 col-lg">
              <div class="single-footer-widget">
                <!-- Widget Title -->
                <h5 class="widget-title">Opening Hours</h5>

                <!-- Opening Hours -->
                <ul class="opening-hours">
                  <li><span>Mon-Wed</span> <span>8.00-18.00</span></li>
                  <li><span>Thu-Fri</span> <span>8.00-17.00</span></li>
                  <li><span>Sat</span> <span>9.00-17.00</span></li>
                  <li><span>Sun</span> <span>10.00-17.00</span></li>
                  <li><span>Holiday</span> <span>Closed</span></li>
                </ul>
              </div>
            </div>

            <!-- Single Footer Widget -->
            <div class="col-12 col-sm-6 col-lg">
              <div class="single-footer-widget">
                <!-- Widget Title -->
                <h5 class="widget-title">Quick Link</h5>

                <!-- Quick Links Nav -->
                <nav>
                  <ul class="quick-links">
                    <li><a href="{% url 'frontend:about' %}">About</a></li>
                    <li><a href="{% url 'frontend:contact' %}">Contact</a></li>
                    <li><a href="{% url 'frontend:about' %}">Dentist</a></li>
                    <li><a href="{% url 'frontend:service' %}">Services</a></li>
                    <li><a href="{% url 'frontend:pricing' %}">pricing</a></li>
                  </ul>
                </nav>
              </div>
            </div>

                <!-- Social Info -->
                <div class="footer-social-info">
                  <a href="https://facebook.com" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
                  <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
                  <a href="#" data-toggle="tooltip" data-placement="top" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                  <a href="#" data-toggle="tooltip" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                  <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>

    <!-- Copywrite Area -->
        <div class="container">
          <div class="row">
            <div class="col-12">
              <div class="copywrite-content">
                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib --- Downloaded from <a href="https://themeslab.org/" target="_blank">Themeslab</a></a>
    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
              </div>
            </div>
          </div>
        </div>
      </footer>
      <!-- ***** Footer Area End ***** -->

      <!-- ******* All JS ******* -->
      <!-- jQuery js -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <!-- Popper js -->
      <script src="{% static 'js/popper.min.js' %}"></script>
      <!-- Bootstrap js -->
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- All js -->
      <script src="{% static 'js/dento.bundle.js' %}"></script>
      <!-- Active js -->
      <script src="{% static 'js/default-assets/active.js' %}"></script>

    </body>

    </html>

frontend/templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!--{% block title %}contact Dr RICHARD{% endblock %}-->
{% block meta_description %}This is the website of doctor Richard, the best dentist{% endblock %}

  <!-- ***** Breadcrumb Area Start ***** -->
<div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'img/bg-img/12.jpg' %});"
     xmlns:https="http://www.w3.org/1999/xhtml">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">Contact</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Contact</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Contact Area Start ***** -->
  {% if message_name %}
    <center>
      <h2>Thanks {{message_name}}</h2>
      <p>We got your mail and would respond shortly</p>
    </center>
    <br/><br/><br/>
  {% else%}
  <section class="dento-contact-area mt-50 mb-100">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="google-maps mb-100">
<!--            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11956.9355465873!2d24.0768412544878!3d56.9550599906977!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46eecfb0e5073ded%3A0x400cfcd68f2fe30!2z4Kaw4Ka_4KaX4Ka-LCDgprLgp43gpq_gpr7gpp_gp43gpq3gpr_gpoY!5e0!3m2!1sbn!2sbd!4v1543911160102"-->
<!--              allowfullscreen></iframe>-->
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4713.955437561931!2d3.3845169115400524!3d6.5282231997774565!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103b8d026f5d7a8d%3A0x9c077cc36ba07e8!2sZest%20International%20Hotel!5e0!3m2!1sen!2sus!4v1642810617933!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

          </div>
        </div>
      </div>

      <div class="row">
        <!-- Contact Information -->
        <div class="col-12 col-md-4">
          <div class="contact-information">
            <h5>Address</h5>
            <p>St Finbarr's College Rd, Akoka 102216, Lagos, Nigeria</p>

            <h5>Phone</h5>
            <p>+234. 8252. 2250. 122</p>

            <h5>Fax</h5>
            <p>+234. 2252. 2250. 125</p>

            <h5>Email</h5>
            <p class="mb-0">info.dento@gmail.com</p>
          </div>
        </div>

        <!-- Contact Form -->
        <div class="col-12 col-md-8">
          <div class="contact-form">
            <!-- Section Heading -->
            <div class="section-heading">
              <h2>Get In Touch -</h2>
              <div class="line"></div>
            </div>
            <!-- Form -->
            <form action="{% url 'frontend:contact' %}" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-lg-6">
                  <input type="text" name="message-name" class="form-control mb-30" placeholder="Your Name">
                </div>
                <div class="col-lg-6">
                  <input type="email" name="message-email" class="form-control mb-30" placeholder="Your Email">
                </div>
                <div class="col-12">
                  <textarea name="message" class="form-control mb-30" placeholder="Your Message"></textarea>
                </div>
                <div class="col-12">
                  <button type="submit" class="btn dento-btn">Send Message</button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </section>
  {% endif %}
  <!-- ***** Contact Area End ***** -->

 {% endblock %}

frontend/templates/service.html
{% extends 'base.html' %}


{% block content %}
{% load static %}

  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">Service</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Service</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Services Area Start ***** -->
  <section class="dento-services-area mt-50 mb-50">
    <div class="container">
      <div class="row">

        <!-- Single Service Area -->
        {% for rs in service %}
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{{rs.images.url}}" alt="">
            </div>
            <h5>{{rs.service_available}}</h5>
            <p>{{rs.details}}</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!-- ***** Services Area End ***** -->
{% endblock %}